function anothervertexcolor
  clear;
  clc;
  file=fopen("c:\\users\\olga\\desktop\\new_object\\datagraph\\gc_1000_9","r");
  v=fscanf(file,"%d",1);
  e=fscanf(file,"%d",1);
  E=zeros(v,v);
  vertcol=zeros(1,v);
  l=zeros(1,2);
  n=1;
  for(k=1:e)
    l(1,1)=fscanf(file,"%d",1)+1;
    l(1,2)=fscanf(file,"%d",1)+1;
    E(l(1,1),l(1,2))=1;
    E(l(1,2),l(1,1))=1;
  endfor
  for(k=1:v)
    E(k,k)=1;
  endfor
  for(k=1:v)
    if(!vertcol(k))
      j=1;
      vertcol(k)=n;
      while(j<=v)
        if((!E(k,j))&&(!vertcol(j)))
          E(k,:)=bitor(E(k,:),E(j,:));
          vertcol(j)=n;
        endif
        j++;
      endwhile
      n++;
    endif
  endfor
  n--;
  n
  vertcol
  fclose(file);
endfunction
